version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'nemshbanking'
      POSTGRES_USER: 'artemartem'
      POSTGRES_PASSWORD: '325159799'
    volumes:
      - postgres_data:/var/lib/postgresql/data # Добавьте том для данных, чтобы сохранять их между перезапусками контейнера

  web:
    build: .
    command: gunicorn SimpleBanking.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db # Добавьте переменные среды, если ваше приложение их использует для подключения к БД
      - DATABASE_NAME=nemshbanking
      - DATABASE_USER=artemartem
      - DATABASE_PASSWORD=325159799

volumes:
  postgres_data:
