version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn -b 0.0.0.0:8000 SimpleBanking.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: nemshbanking
      POSTGRES_USER: artemartem
      POSTGRES_PASSWORD: 325159799
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: