# Generated by Django 4.2.5 on 2024-02-26 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('identification_number', models.PositiveIntegerField(db_comment='Personal identification number with 8 digits', default=10, unique=True, validators=[django.core.validators.MinValueValidator(10000000)])),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
    ]
