# Generated by Django 5.0.2 on 2024-02-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_account_first_name_account_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
