# Generated by Django 4.2.5 on 2024-02-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_account_first_name_alter_account_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
